---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
      - image: obazacr.azurecr.io/keoffor/email-app
        imagePullPolicy: Always
        name: email-container
        ports:
        - containerPort: 8001

#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
# name: reimburse-monitor
#spec:
# selector:
#   matchLabels:
#     app: service-app
# endpoints:
#   - port: service-http
#     path: "/actuator/prometheus"
