---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
      - image: keoffor/email-app
        imagePullPolicy: Always
        name: email-container
        ports:
        - containerPort: 8001
