---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
      - image: keoffor/email:v1
        imagePullPolicy: Always
        name: email-container
        ports:
        - containerPort: 8001


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-app
  name: email-service
spec:
  type: LoadBalancer
  ports:
    - name: email-https
      port: 8001
      targetPort: 8001
  selector:
    app: email-app
#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
# name: reimburse-monitor
#spec:
# selector:
#   matchLabels:
#     app: service-app
# endpoints:
#   - port: service-http
#     path: "/actuator/prometheus"
