apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-app
  name: email-service
spec:
  type: LoadBalancer
  ports:
    - name: email-https
      port: 8001
      targetPort: 8001
  selector:
    app: email-app